name: Story
description: User story under a Feature
title: "SN.x.y: "
labels: ["type:story"]
body:
  - type: markdown
    attributes:
      value: |
        ## Naming Convention
        Replace `N.x.y` in the title with the parent epic, feature, and story sequence.
        Example: `S9K.1.1:`, `S10.3.2:`, `S11A.2.1:`

  - type: input
    id: parent-feature
    attributes:
      label: Parent Feature
      description: Reference the parent feature issue
      placeholder: "#168"
    validations:
      required: true

  - type: textarea
    id: narrative
    attributes:
      label: User Story
      description: Use the standard narrative format
      value: |
        As a **<role>**,
        I want **<capability>**,
        so that **<outcome>**.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Use GIVEN/WHEN/THEN format where possible
      placeholder: |
        GIVEN <condition>
        WHEN <action>
        THEN <result>
    validations:
      required: true

  - type: input
    id: pbs-id
    attributes:
      label: PBS ID
      description: Product Breakdown Structure identifier
      placeholder: "PBS-2.1"
    validations:
      required: false

  - type: input
    id: wbs-code
    attributes:
      label: WBS Code
      description: Work Breakdown Structure code
      placeholder: "2.1.1"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: false

  - type: input
    id: estimate
    attributes:
      label: Estimate
      description: Story points or hours
      placeholder: "3 points"
    validations:
      required: false
